import { useState } from "react";
import { Trophy, DollarSign, CheckCircle2, Sparkles, BarChart3, Zap, Info } from "lucide-react";
import { Card } from "./common";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogDescription,
} from "./ui/dialog";

const DEFS = [
  { key: "overall", title: "Overall Competitive Score", unit: "/100", Icon: Trophy, accent: "text-blue-400", pct: (v) => v },
  { key: "price_competitiveness", title: "Price Competitiveness", unit: "/10", Icon: DollarSign, accent: "text-emerald-400", pct: (v) => v * 10 },
  { key: "feature_strength", title: "Feature Strength", unit: "%", Icon: CheckCircle2, accent: "text-cyan-400", pct: (v) => v },
  { key: "value_prop", title: "Value Proposition", unit: "/10", Icon: Sparkles, accent: "text-indigo-400", pct: (v) => v * 10 },
  { key: "market_position", title: "Market Position", unit: "rank", Icon: BarChart3, accent: "text-amber-400", pct: (v) => Math.max(0, 100 - (v - 1) * 18), fmt: (v) => `#${v}` },
  { key: "innovation", title: "Innovation Score", unit: "/10", Icon: Zap, accent: "text-fuchsia-400", pct: (v) => v * 10 },
];

export default function ScoreCards({ scores }) {
  const s = scores || {};
  return (
    <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4">
      {DEFS.map((d, i) => {
        const raw = s[d.key];
        const has = raw !== undefined && raw !== null;
        const pct = has ? Math.min(100, Math.max(4, d.pct(raw))) : 0;
        return (
          <Card key={d.key} testid={`score-card-${d.key}`} className="p-5 hover:border-[#374151] transition-colors animate-fade-up" >
            <div className="flex items-center justify-between mb-4">
              <div className={`w-9 h-9 rounded-lg bg-[#1F2937] flex items-center justify-center ${d.accent}`}>
                <d.Icon className="w-4.5 h-4.5" style={{ width: 18, height: 18 }} />
              </div>
              {i === 0 && <MethodologyDialog />}
            </div>
            <div className="flex items-baseline gap-1">
              <span className="font-heading text-3xl font-extrabold text-slate-50" data-testid={`score-value-${d.key}`}>
                {has ? (d.fmt ? d.fmt(raw) : raw) : "—"}
              </span>
              <span className="text-slate-500 text-sm font-medium">{d.unit}</span>
            </div>
            <div className="text-[13px] text-slate-400 mt-1 leading-tight">{d.title}</div>
            <div className="mt-3 h-1.5 rounded-full bg-[#1F2937] overflow-hidden">
              <div className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-400 transition-all duration-700" style={{ width: `${pct}%` }} />
            </div>
          </Card>
        );
      })}
    </div>
  );
}

function MethodologyDialog() {
  const [open, setOpen] = useState(false);
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <button data-testid="methodology-btn" className="text-slate-500 hover:text-blue-400 transition-colors">
          <Info className="w-4 h-4" />
        </button>
      </DialogTrigger>
      <DialogContent className="bg-[#111827] border-[#374151] text-slate-200 max-w-lg">
        <DialogHeader>
          <DialogTitle className="font-heading text-slate-50">How is this calculated?</DialogTitle>
          <DialogDescription className="text-slate-400">
            These are <span className="text-amber-400 font-medium">AI-derived competitive scores</span>, not objective facts.
          </DialogDescription>
        </DialogHeader>
        <div className="text-sm text-slate-300 space-y-3 leading-relaxed">
          <p><span className="text-slate-100 font-semibold">Overall Score</span> blends feature coverage (35%), pricing competitiveness (25%), value proposition (20%) and innovation (20%).</p>
          <p><span className="text-slate-100 font-semibold">Feature Strength</span> = supported features ÷ total tracked features across all competitors.</p>
          <p><span className="text-slate-100 font-semibold">Price Competitiveness</span> reflects your relative starting price vs the competitive set (higher = more affordable).</p>
          <p className="text-slate-400 text-xs pt-2 border-t border-[#1f2937]">Scores are generated by GPT-5.4 from collected and inferred data. Treat them as directional guidance.</p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
